// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repo

import (
	"time"
)

type Accessibility struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
}

type AccessibilityListing struct {
	AccessibilityID int32 `json:"accessibility_id"`
	ListingID       int32 `json:"listing_id"`
}

type Address struct {
	ID                int64  `json:"id"`
	ListingID         int32  `json:"listing_id"`
	Country           string `json:"country"`
	Province          string `json:"province"`
	Wijk              string `json:"wijk"`
	City              string `json:"city"`
	Neighbourhood     string `json:"neighbourhood"`
	HouseNumberSuffix string `json:"house_number_suffix"`
	Municipality      string `json:"municipality"`
	IsBagAddress      bool   `json:"is_bag_address"`
	HouseNumber       string `json:"house_number"`
	PostalCode        string `json:"postal_code"`
	StreetName        string `json:"street_name"`
}

type Agent struct {
	ID          int64  `json:"id"`
	LogoType    string `json:"logo_type"`
	RelativeUrl string `json:"relative_url"`
	IsPrimary   bool   `json:"is_primary"`
	LogoID      int32  `json:"logo_id"`
	Name        string `json:"name"`
	Association string `json:"association"`
}

type AgentListing struct {
	ListingID int32 `json:"listing_id"`
	AgentID   int32 `json:"agent_id"`
}

type Amenity struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
}

type AmenityListing struct {
	AmenityID int32 `json:"amenity_id"`
	ListingID int32 `json:"listing_id"`
}

type FloorAreaRange struct {
	ID  int64 `json:"id"`
	Gte int32 `json:"gte"`
	Lte int32 `json:"lte"`
}

type Listing struct {
	ID                 int64       `json:"id"`
	PlacementType      string      `json:"placement_type"`
	NumberOfBathrooms  int32       `json:"number_of_bathrooms"`
	NumberOfBedrooms   int32       `json:"number_of_bedrooms"`
	NumberOfRooms      int32       `json:"number_of_rooms"`
	RelevancySortOrder int32       `json:"relevancy_sort_order"`
	EnergyLabel        string      `json:"energy_label"`
	Availability       string      `json:"availability"`
	Type               string      `json:"type"`
	Zoning             string      `json:"zoning"`
	TimeStamp          time.Time   `json:"time_stamp"`
	ObjectType         string      `json:"object_type"`
	ConstructionType   string      `json:"construction_type"`
	PublishDateUtc     time.Time   `json:"publish_date_utc"`
	PublishDate        time.Time   `json:"publish_date"`
	RelativeUrl        string      `json:"relative_url"`
	PlotAreaRangeID    int32       `json:"plot_area_range_id"`
	FloorAreaRangeID   int32       `json:"floor_area_range_id"`
	SellPrice          int32       `json:"sell_price"`
	RentPrice          int32       `json:"rent_price"`
	Geohash            interface{} `json:"geohash"`
}

type MediaType struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
}

type MediaTypeListing struct {
	ListingID   int32 `json:"listing_id"`
	MediaTypeID int32 `json:"media_type_id"`
}

type OfferingType struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
}

type OfferingTypeListing struct {
	ListingID      int32 `json:"listing_id"`
	OfferingTypeID int32 `json:"offering_type_id"`
}

type Parking struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
}

type ParkingListing struct {
	ListingID int32 `json:"listing_id"`
	ParkingID int32 `json:"parking_id"`
}

type PlotAreaRange struct {
	ID  int64 `json:"id"`
	Gte int32 `json:"gte"`
	Lte int32 `json:"lte"`
}

type Surrounding struct {
	ID   int64  `json:"id"`
	Text string `json:"text"`
}

type SurroundingListing struct {
	ListingID     int32 `json:"listing_id"`
	SurroundingID int32 `json:"surrounding_id"`
}

type Thumbnail struct {
	ID        int64 `json:"id"`
	ListingID int32 `json:"listing_id"`
	Img       int32 `json:"img"`
}
